spring.application.name=TechBazaar

#Database configuration 
# ✅ Correct JDBC URL
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:29403/railway

# ✅ Direct values
spring.datasource.username=root
spring.datasource.password=PRjqnJmwfaWDDdZVteFsxbyesxeHMLin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ✅ Server
server.port=${PORT:8080}

#Database permission
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#Project Running Server Port
server.port = 8282

#file size configuration
spring.servlet.multipart.max-file-size = 25MB
spring.servlet.multipart.max-request-size = 25MB



#E-mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kumarguptaraj825@gmail.com
spring.mail.password=cneioftyfeghyftv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

razorpay.key=rzp_live_Io1s9ctQtD0G1b
razorpay.secret=HO60ThPu65xyvH7ewH5eVcWp

