spring.application.name=TechBazaar

#Database configuration 
# ✅ Correct JDBC URL
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:29403/railway

# ✅ Direct values
spring.datasource.username=root
spring.datasource.password=PRjqnJmwfaWDDdZVteFsxbyesxeHMLin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ✅ Server
server.port=${PORT:8080}

#Database permission
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#Project Running Server Port
server.port = 8282

#file size configuration
spring.servlet.multipart.max-file-size = 25MB
spring.servlet.multipart.max-request-size = 25MB



#E-mail Configuration
# Gmail SMTP configuration
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = kumarguptaraj825@gmail.com
spring.mail.password = vkgh qrhm oher ikcp
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.connectiontimeout = 10000
spring.mail.properties.mail.smtp.timeout = 10000
spring.mail.properties.mail.smtp.writetimeout = 10000
spring.mail.properties.mail.debug = true

razorpay.key=rzp_live_Io1s9ctQtD0G1b
razorpay.secret=HO60ThPu65xyvH7ewH5eVcWp

